image: maven:3.3.9
pipelines:
  default:
    - step:
        name: Build application
        trigger: automatic
        caches:
          - maven # Cache any dependencies we download, speeds up build times.
        script:
          - mvn clean install -pl account-app -am